### PR TITLE
feat(prefect-worker): support extra initContainers

### LINKED ISSUE #393: Add option for creating additional Init Containers for Workers
Currently Workers have an optional Init Container defined for syncing a base job template from a configmap. However, it would be useful to have additional optional init containers for any setup work that a user would want to have completed before the Worker starts up. 

Our team specifically would like to use the init containers to deploy deployments associated with the workers. So when a worker starts, all the necessary deployments will be present in the Prefect UI. 

I will have a PR for this open in the coming days.

### PR DESCRIPTION
**Pull request by NiJuFirenzia**
Providing option to create extra Init Containers for Workers. The Init Containers are set up as optional in addition to the Init Container that is already present in the worker to allow for syncing basejob template. A definition for "extraContainers" has been added.

Resolves https://github.com/PrefectHQ/prefect-helm/issues/393

### CODE REVIEW

**Comment by jamiezieziula** [comment]
Hi @NiJuFirenzia - thanks for the contribution! Looks like theres just a few linting errors. Once those are fixed, I'll be happy to merge.

**Comment by mitchnielsen** [comment]
And bonus points if you add test(s)! https://github.com/PrefectHQ/prefect-helm/blob/main/charts/prefect-worker/tests/worker_test.yaml

**Comment by NiJuFirenzia** [comment]
Hi @jamiezieziula and @mitchnielsen, I added a test case for the additional extra containers and fixed the lint error. Let me know if anything else is needed.

**Review by mitchnielsen — APPROVED** [review]

**Comment by mitchnielsen** [comment]
Thanks for the contribution @NiJuFirenzia!

**Pull request merged**
