### PR TITLE
/opt/prefect needs to be writable for memo_store.toml

### PR DESCRIPTION
**Pull request by mluscon**
Without this PR orion fails on startup:

```
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 645, in lifespan
    async with self.lifespan_context(app):
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 540, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 622, in startup
    await handler()
  File "/usr/local/lib/python3.10/site-packages/prefect/orion/api/server.py", line 288, in wrapper
    memo_store_path.write_text(
  File "/usr/local/lib/python3.10/pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "/usr/local/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
OSError: [Errno 30] Read-only file system: '/opt/prefect/memo_store.toml'
ERROR:    Application startup failed. Exiting.
Orion stopped!
```

### CODE REVIEW

**Comment by madkinsz** [comment]
@desertaxle we should probably write this file best-effort and not crash the application if it's read-only.

**Comment by desertaxle** [comment]
> @desertaxle we should probably write this file best-effort and not crash the application if it's read-only.

For sure. I'll implement that in the core library. Another valid approach could be to disable block auto-registration memoization in the helm chart with the `PREFECT_MEMOIZE_BLOCK_AUTO_REGISTRATION` setting.

**Comment by jawnsy** [comment]
Hey @mluscon, thanks for reporting this issue and offering a PR! I've solved this problem using a different approach in #67, by mounting a writable home directory and `/tmp` directory. Can you take a look at that and see whether it resolves your issue?

**Comment by jamiezieziula** [comment]
superseded by https://github.com/PrefectHQ/prefect-helm/pull/67#pullrequestreview-1130737267

**Pull request closed without merging**
