### PR TITLE
Adds option to specify workPool

### PR DESCRIPTION
**Pull request by EmilRex**
Adds option to set a single `workPool` in chart.

Still need to test the change to verify that existing behavior isn't changed and new behavior is.

### CODE REVIEW

**Review by jamiezieziula — DISMISSED** [review]
lgtm

**Review by parkedwards — DISMISSED** [review]

**Review by jimid27 — DISMISSED** [review]
nice looks good

**Comment by jicuss** [comment]
this would be super helpful to me

**Comment by Bada-S** [comment]
Hey y'all, I tested out the chart locally. I pulled down Emil's chart and deployed the agent on minikube. I ended up hardcoding the work pool for the sake of testing, but it was able to deploy the agent successfully. @EmilRex If you can sync sometime I can show you how I tested the chart

**Comment by EmilRex** [comment]
Alright... I made (and tested) some changes to the default behavior. Now if neither `workPool` nor `workQueues` are specified, we just listen to the default work queue. This ensures that the default behavior of the chart remains unchanged. Then, if either (or both) `workPool` or `workQueues` is specified, we fill them in as appropriate.

@jimid27 Does that make sense to you?

**Review by jimid27 — APPROVED** [review]
This lgtm!

**Pull request merged**
