### PR TITLE
feat(base-job-template): Add base job template name

### PR DESCRIPTION
**Pull request by lucas-koontz**
This PR introduces a `baseJobTemplateName` to `prefect-worker` allowing the use of different base job templates for different workers within the same namespaces.

### CODE REVIEW

**Review by jamiezieziula — APPROVED** [review]
lgtm - thanks for your contribution!

**Comment by lucas-koontz** [comment]
> lgtm - thanks for your contribution!

Thank you @jamiezieziula!

Also, all lint and tests are failing for the same reason:
```
Error: INSTALLATION FAILED: execution error at (prefect-worker/templates/_helpers.tpl:72:86): A Prefect Cloud Account ID is required (worker.cloudApiConfig.accountId)
```
Have you ran into this issue before?

**Comment by jamiezieziula** [comment]
@lucas-koontz yes I have and of course I can't remember what the cause was. I'm fairly confident this change is safe. I'll try to fix the lint tests tomorrow but if I don't get to it I'll test locally and merge!

**Comment by lucas-koontz** [comment]
> @lucas-koontz yes I have and of course I can't remember what the cause was. I'm fairly confident this change is safe. I'll try to fix the lint tests tomorrow but if I don't get to it I'll test locally and merge!

Thank you so much!

**Pull request merged**
